Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 25
Metrics/ModuleLength:
  Max: 150 # spec fils
Metrics/AbcSize:
  Enabled: false
Metrics/ParameterLists:
  Max: 6
Documentation:
  Enabled: false
