require 'nokogiri'
require 'logger'

# tools
require 'tools/tools'
require 'tools/point'
require 'tools/geometry'
require 'tools/array'
require 'tools/string'
require 'tools/numeric'
require 'tools/logger'
require 'tools/hash'

# svg
require 'svg/svg'
require 'svg/svg_tools'
require 'svg/elements/svg_arguments'
require 'svg/elements/svg_element'
require 'svg/elements/svg_group'
require 'svg/elements/svg_line'
require 'svg/elements/svg_text'
require 'svg/elements/svg_polygon'
require 'svg/elements/svg_path'

# elements
require 'objects/helpers/wall_helper'
require 'objects/factories/room_factory'
require 'objects/factories/wall_factory'
require 'objects/wall_segment'
require 'objects/room'
require 'objects/wall'
require 'objects/opening'
require 'objects/window'
require 'objects/door'

# main
require 'run/transformations/wall_merger'
require 'run/transformations/wall_filler'
require 'run/ruby_parser/ruby_data_loader'
require 'run/ruby_parser/ruby_to_yaml_loader'
require 'run/runner'
require 'run/wall_pool'
require 'run/yaml_parser/yaml_data_loader'
require 'run/yaml_parser/yaml_room_factory'
require 'run/yaml_parser/yaml_wall_factory'
